Subject.create(name: "CALCULO DIFERENCIAL", mid: 1000004)
Subject.create(name: "INTRODUCCION A LA INGENIERIA DE SISTEMAS Y COMPUTACION", mid: 2025975)
Subject.create(name: "PROGRAMACION DE COMPUTADORES",mid: 2015734)
Subject.create(name: "FUNDAMENTOS DE MECANICA", mid: 1000019)
Subject.create(name: "CALCULO INTEGRA", mid: 1000005)
Subject.create(name: "ALGEBRA LINEAL", mid: 1000003)
Subject.create(name: "PROGRAMACION ORIENTADA A OBJETOS", mid: 2016375)
Subject.create(name: "PROBABILIDAD Y ESTADISTICA", mid: 1000013)
Subject.create(name: "CALCULO EN VARIAS VARIABLES", mid: 1000006)
Subject.create(name: "MATEMATICAS DISCRETAS I", mid: 2025963)
Subject.create(name: "BASES DE DATOS", mid: 2016353)
Subject.create(name: "ELEMENTOS DE COMPUTADORES", mid: 2016698)
Subject.create(name: "FUNDAMENTOS DE ELECTRICIDAD Y MAGNETISMO", mid: 1000017)
Subject.create(name: "INGENIERIA ECONOMICA", mid: 2015703)
Subject.create(name: "MATEMATICAS DISCRETAS II", mid: 2025964)
Subject.create(name: "ESTRUCTURAS DE DATOS", mid: 2016699)
Subject.create(name: "ARQUITECTURA DE COMPUTADORES", mid: 2016697)
Subject.create(name: "MODELOS Y SIMULACION", mid: 2025970)
Subject.create(name: "GERENCIA Y GESTION DE PROYECTOS", mid: 2015702)
Subject.create(name: "REDES DE COMPUTADORES", mid: 2025967)
Subject.create(name: "INGENIERIA DE SOFTWARE", mid: 2016701)
Subject.create(name: "INTRODUCCION A LA TEORIA DE COMPUTACION", mid: 2015174)
Subject.create(name: "OPTIMIZACION", mid: 2025971)
Subject.create(name: "METODOS NUMERICOS", mid: 2015970)
Subject.create(name: "SISTEMAS DE INFORMACION", mid: 2025982)
Subject.create(name: "INGENIERIA DE SOFTWARE II", mid: 2016702)
Subject.create(name: "ALGORITMOS", mid: 2016696)
Subject.create(name: "SISTEMAS OPERATIVOS", mid: 2016707)
Subject.create(name: "MODELOS ESTOCASTICOS Y SIMULACION EN COMPUTACION Y COMUNICACIONES", mid: 2025969)
Subject.create(name: "INFORMACION Y COMUNICACIONES", mid: 2025994)
Subject.create(name: "PENSAMIENTO SISTEMICO", mid: 2016703)
Subject.create(name: "OPTATIVA EN METODOS Y TECNOLOGIAS DE SOFTWARE", mid: 2016716)
Subject.create(name: "LENGUAJES DE PROGRAMACION", mid: 2025966)
Subject.create(name: "SISTEMAS INTELIGENTES", mid: 2025995)
Subject.create(name: "COMPUTACION PARALELA Y DISTRIBUIDA", mid: 2025968)
Subject.create(name: "COMPUTACION VISUAL", mid: 2025960)
Subject.create(name: "TALLER DE PROYECTOS INTERDISCIPLINARIOS", mid: 2024045)
Subject.create(name: "ARQUITECTURA DE INFRAESTRUCTURA Y GOBIERNO DE TICS", mid: 2025983)
Subject.create(name: "CRIPTOGRAFIA Y SEGURIDAD DE LA INFORMACION", mid: 2025972)


User.create(identification: 797363533, name:"Hector Villa", student:true, gender:'M',  career:"Ingenieria Sistemas", city:"San Gil", aboutme:"No yet implements")
User.create(identification: 42346768, name:"Patricia Díaz", student:true, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 87654543, name:"Mery Pinzón", student:true, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1234567889, name:"Laura Mendez", student:true, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1097364463, name:"Oscar Pulido", student:true, gender:'M',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1290837643, name:"Gustavo Gongora", student:true, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 87654444, name:"Aura Melo", student:true, gender:'F',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 56780086, name:"William Angel", student:true, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1244567788, name:"Gerson Buitrago", student:true, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1024444445, name:"Beatriz Botero", student:true, gender:'F',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1123098746, name:"Cristian Suarez", student:true, gender:'M',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1309887654, name:"Monica Mojica", student:true, gender:'F',  career:"Ingenieria Sistemas", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1083837353, name:"Hernando Vargas", student:true, gender:'M',  career:"Ingenieria Sistemas", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1082736353, name:"Erica Suarez", student:true, gender:'F',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1083733545, name:"Henry Rodriguez", student:true, gender:'M',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1126553839, name:"Franklin Acosta", student:true, gender:'M',  career:"Ingenieria Electrica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1109000987, name:"Deyanira Lopez", student:true, gender:'F',  career:"Ingenieria Electrica", city:"Manizales", aboutme:"No yet implements")
User.create(identification: 1093938474, name:"Alejandro Puentes", student:true, gender:'M',  career:"Ingenieria Electrónica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1275849494, name:"Jefferson Ramirez", student:true, gender:'M',  career:"Ingenieria Electrónica", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1102843674, name:"Leydi Hernandez", student:true, gender:'F',  career:"Ingenieria Quimica", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1038374645, name:"Paula Arias", student:true, gender:'F',  career:"Ingenieria Quimica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1090000101, name:"Pedro Paramo", student:true, gender:'M',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1100908761, name:"Tom Sawyer", student:true, gender:'M',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")

User.create(identification: 88082727, name:"Gonzalo Jimenez", student:false, gender:'M',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 71616161, name:"Leydi Cardozo", student:false, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 54333322, name:"Juanito Alimaña", student:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1010101010, name:"Pedro Navajas", student:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1111111111, name:"Hector Lavoe", student:false, gender:'M',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1222222222, name:"Celia Cruz", student:false, gender:'F',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1333333333, name:"Miriam Urrego", student:false, gender:'F',  career:"Ingenieria Sistemas", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1444444444, name:"María Peña", student:false, gender:'F',  career:"Ingenieria Sistemas", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1555555555, name:"Nestor Nope", student:false, gender:'M',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1666666666, name:"Angie Beltran", student:false, gender:'F',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1777777777, name:"Pepito Perez", student:false, gender:'M',  career:"Ingenieria Electrica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1888888888, name:"Magda Lourdes", student:false, gender:'F',  career:"Ingenieria Electrica", city:"Manizales", aboutme:"No yet implements")
User.create(identification: 1999999999, name:"Xavier Garden", student:false, gender:'M',  career:"Ingenieria Electrónica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1028846455, name:"Daniela Castillo", student:false, gender:'F',  career:"Ingenieria Electrónica", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1098765432, name:"Ana Sanchez", student:false, gender:'F',  career:"Ingenieria Quimica", city:"Medellín", aboutme:"No yet implements")
User.create(identification: 1012345667, name:"Ana Mera", student:false, gender:'F',  career:"Ingenieria Quimica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1084367435, name:"Silvia Silva", student:true, gender:'F',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
User.create(identification: 1109764322, name:"Sandra Castro", student:true, gender:'F',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
