# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Career.create(name: 'Administración de Empresas')
Career.create(name: 'Antropología')
Career.create(name: 'Arquitectura')
Career.create(name: 'Artes Plásticas')
Career.create(name: 'Biología')
Career.create(name: 'Ciencia Política')
Career.create(name: 'Cine y Televisión')
Career.create(name: 'Contaduría Pública')
Career.create(name: 'Derecho')
Career.create(name: 'Diseño Gráfico')
Career.create(name: 'Diseño Industrial')
Career.create(name: 'Economía')
Career.create(name: 'Enfermería')
Career.create(name: 'Español y Filología Clásica')
Career.create(name: 'Estadística')
Career.create(name: 'Estudios Literarios')
Career.create(name: 'Farmacia')
Career.create(name: 'Filología e Idiomas - Español y Humanidades Básicas')
Career.create(name: 'Filología e Idiomas Alemán')
Career.create(name: 'Filología e Idiomas Francés')
Career.create(name: 'Filología e Idiomas Inglés')
Career.create(name: 'Filosofía')
Career.create(name: 'Física')
Career.create(name: 'Fisioterapia')
Career.create(name: 'Fonoaudiología')
Career.create(name: 'Geografía')
Career.create(name: 'Geología')
Career.create(name: 'Historia')
Career.create(name: 'Ingeniería Agrícola')
Career.create(name: 'Ingeniería Agronómica')
Career.create(name: 'Ingeniería Civil')
Career.create(name: 'Ingeniería de Sistemas y Computación')
Career.create(name: 'Ingeniería Eléctrica')
Career.create(name: 'Ingeniería Electrónica')
Career.create(name: 'Ingeniería Industrial')
Career.create(name: 'Ingeniería Mecánica')
Career.create(name: 'Ingeniería Mecatrónica')
Career.create(name: 'Ingeniería Química')
Career.create(name: 'Lingüística')
Career.create(name: 'Matemáticas')
Career.create(name: 'Medicina')
Career.create(name: 'Medicina Veterinaria')
Career.create(name: 'Música')
Career.create(name: 'Música Instrumental')
Career.create(name: 'Nutrición y Dietética')
Career.create(name: 'Odontología')
Career.create(name: 'Psicología')
Career.create(name: 'Química')
Career.create(name: 'Sociología')
Career.create(name: 'Terapia Ocupacional')
Career.create(name: 'Trabajo Social')
Career.create(name: 'Zootecnia')

Subject.create(mid: 1000004, name: "CALCULO DIFERENCIAL", description: "none")
Subject.create(mid: 2025975, name: "INTRODUCCION A LA INGENIERIA DE SISTEMAS Y COMPUTACION", description: "none")
Subject.create(mid: 2015734, name: "PROGRAMACION DE COMPUTADORES", description: "none")
Subject.create(mid: 1000019, name: "FUNDAMENTOS DE MECANICA", description: "none")
Subject.create(mid: 1000005, name: "CALCULO INTEGRA", description: "none")
Subject.create(mid: 1000003, name: "ALGEBRA LINEAL", description: "none")
Subject.create(mid: 2016375, name: "PROGRAMACION ORIENTADA A OBJETOS", description: "N.A")
Subject.create(mid: 1000013, name: "PROBABILIDAD Y ESTADISTICA", description: "N.A")
Subject.create(mid: 1000006, name: "CALCULO EN VARIAS VARIABLES", description: "N.A")
Subject.create(mid: 2025963, name: "MATEMATICAS DISCRETAS I", description: "N.A")
Subject.create(mid: 2016353, name: "BASES DE DATOS", description: "N.A")
Subject.create(mid: 2016698, name: "ELEMENTOS DE COMPUTADORES", description: "N.A")
Subject.create(mid: 1000017, name: "FUNDAMENTOS DE ELECTRICIDAD Y MAGNETISMO", description: "N.A")
Subject.create(mid: 2015703, name: "INGENIERIA ECONOMICA", description: "N.A")
Subject.create(mid: 2025964, name: "MATEMATICAS DISCRETAS II", description: "N.A")
Subject.create(mid: 2016699, name: "ESTRUCTURAS DE DATOS", description: "N.A")
Subject.create(mid: 2016697, name: "ARQUITECTURA DE COMPUTADORES", description: "N.A")
Subject.create(mid: 2025970, name: "MODELOS Y SIMULACION", description: "")
Subject.create(mid: 2015702, name: "GERENCIA Y GESTION DE PROYECTOS", description: "")
Subject.create(mid: 2025967, name: "REDES DE COMPUTADORES", description: "")
Subject.create(mid: 2016701, name: "INGENIERIA DE SOFTWARE", description: "")
Subject.create(mid: 2015174, name: "INTRODUCCION A LA TEORIA DE COMPUTACION", description: "")
Subject.create(mid: 2025971, name: "OPTIMIZACION", description: "")
Subject.create(mid: 2015970, name: "METODOS NUMERICOS", description: "")
Subject.create(mid: 2025982, name: "SISTEMAS DE INFORMACION", description: "")
Subject.create(mid: 2016702, name: "INGENIERIA DE SOFTWARE II", description: "")
Subject.create(mid: 2016696, name: "ALGORITMOS", description: "")
Subject.create(mid: 2016707, name: "SISTEMAS OPERATIVOS", description: "")
Subject.create(mid: 2025969, name: "MODELOS ESTOCASTICOS Y SIMULACION EN COMPUTACION Y COMUNICACIONES", description: "")
Subject.create(mid: 2025994, name: "INFORMACION Y COMUNICACIONES", description: "ninguna")
Subject.create(mid: 2016703, name: "PENSAMIENTO SISTEMICO", description: "ninguna")
Subject.create(mid: 2016716, name: "OPTATIVA EN METODOS Y TECNOLOGIAS DE SOFTWARE", description: "ninguna")
Subject.create(mid: 2025966, name: "LENGUAJES DE PROGRAMACION", description: "ninguna")
Subject.create(mid: 2025995, name: "SISTEMAS INTELIGENTES", description: "ninguna")
Subject.create(mid: 2025968, name: "COMPUTACION PARALELA Y DISTRIBUIDA", description: "ninguna")
Subject.create(mid: 2025960, name: "COMPUTACION VISUAL", description: "ninguna")
Subject.create(mid: 2024045, name: "TALLER DE PROYECTOS INTERDISCIPLINARIOS", description: "ninguna")
Subject.create(mid: 2025983, name: "ARQUITECTURA DE INFRAESTRUCTURA Y GOBIERNO DE TICS", description: "ninguna")
Subject.create(mid: 2025972, name: "CRIPTOGRAFIA Y SEGURIDAD DE LA INFORMACION", description: "ninguna")

