# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Student_create_group.create(nombre: "WagonDev", maxIntegrantes:5, descripcion:"Ingenieria de Software II", imagen:"")
#Student_create_group.create(nombre: "WagonDev", maxIntegrantes:5, descripcion:"Ingenieria de Software II", imagen:"")


Subject.create(name: "CALCULO DIFERENCIAL", idSubject: 1000004)
Subject.create(name: "INTRODUCCION A LA INGENIERIA DE SISTEMAS Y COMPUTACION", idSubject: 2025975)
Subject.create(name: "PROGRAMACION DE COMPUTADORES",idSubject: 2015734)
Subject.create(name: "FUNDAMENTOS DE MECANICA", idSubject: 1000019)
Subject.create(name: "CALCULO INTEGRAL", idSubject: 1000005)
Subject.create(name: "ALGEBRA LINEAL", idSubject: 1000003)
Subject.create(name: "PROGRAMACION ORIENTADA A OBJETOS", idSubject: 2016375)
Subject.create(name: "PROBABILIDAD Y ESTADISTICA", idSubject: 1000013)
Subject.create(name: "CALCULO EN VARIAS VARIABLES", idSubject: 1000006)
Subject.create(name: "MATEMATICAS DISCRETAS I", idSubject: 2025963)
Subject.create(name: "BASES DE DATOS", idSubject: 2016353)
Subject.create(name: "ELEMENTOS DE COMPUTADORES", idSubject: 2016698)
Subject.create(name: "FUNDAMENTOS DE ELECTRICIDAD Y MAGNETISMO", idSubject: 1000017)
Subject.create(name: "INGENIERIA ECONOMICA", idSubject: 2015703)
Subject.create(name: "MATEMATICAS DISCRETAS II", idSubject: 2025964)
Subject.create(name: "ESTRUCTURAS DE DATOS", idSubject: 2016699)
Subject.create(name: "ARQUITECTURA DE COMPUTADORES", idSubject: 2016697)
Subject.create(name: "MODELOS Y SIMULACION", idSubject: 2025970)
Subject.create(name: "GERENCIA Y GESTION DE PROYECTOS", idSubject: 2015702)
Subject.create(name: "REDES DE COMPUTADORES", idSubject: 2025967)
Subject.create(name: "INGENIERIA DE SOFTWARE", idSubject: 2016701)
Subject.create(name: "INTRODUCCION A LA TEORIA DE COMPUTACION", idSubject: 2015174)
Subject.create(name: "OPTIMIZACION", idSubject: 2025971)
Subject.create(name: "METODOS NUMERICOS", idSubject: 2015970)
Subject.create(name: "SISTEMAS DE INFORMACION", idSubject: 2025982)
Subject.create(name: "INGENIERIA DE SOFTWARE II", idSubject: 2016702)
Subject.create(name: "ALGORITMOS", idSubject: 2016696)
Subject.create(name: "SISTEMAS OPERATIVOS", idSubject: 2016707)
Subject.create(name: "MODELOS ESTOCASTICOS Y SIMULACION EN COMPUTACION Y COMUNICACIONES", idSubject: 2025969)
Subject.create(name: "INFORMACION Y COMUNICACIONES", idSubject: 2025994)
Subject.create(name: "PENSAMIENTO SISTEMICO", idSubject: 2016703)
Subject.create(name: "OPTATIVA EN METODOS Y TECNOLOGIAS DE SOFTWARE", idSubject: 2016716)
Subject.create(name: "LENGUAJES DE PROGRAMACION", idSubject: 2025966)
Subject.create(name: "SISTEMAS INTELIGENTES", idSubject: 2025995)
Subject.create(name: "COMPUTACION PARALELA Y DISTRIBUIDA", idSubject: 2025968)
Subject.create(name: "COMPUTACION VISUAL", idSubject: 2025960)
Subject.create(name: "TALLER DE PROYECTOS INTERDISCIPLINARIOS", idSubject: 2024045)
Subject.create(name: "ARQUITECTURA DE INFRAESTRUCTURA Y GOBIERNO DE TICS", idSubject: 2025983)
Subject.create(name: "CRIPTOGRAFIA Y SEGURIDAD DE LA INFORMACION", idSubject: 2025972)

Person.create(nident: 797363533, name:"Hector Villa", administrator: true, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Sistemas", city:"San Gil", aboutme:"No yet implements")
Person.create(nident: 42346768, name:"Patricia Díaz", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 87654543, name:"Mery Pinzón", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1234567889, name:"Laura Mendez", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1097364463, name:"Oscar Pulido", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1290837643, name:"Gustavo Gongora", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 87654444, name:"Aura Melo", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 56780086, name:"William Angel", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1244567788, name:"Gerson Buitrago", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1024444445, name:"Beatriz Botero", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1123098746, name:"Cristian Suarez", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1309887654, name:"Monica Mojica", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Sistemas", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1083837353, name:"Hernando Vargas", administrator: true, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Sistemas", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1082736353, name:"Erica Suarez", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1083733545, name:"Henry Rodriguez", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1126553839, name:"Franklin Acosta", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Electrica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1109000987, name:"Deyanira Lopez", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Electrica", city:"Manizales", aboutme:"No yet implements")
Person.create(nident: 1093938474, name:"Alejandro Puentes", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Electrónica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1275849494, name:"Jefferson Ramirez", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Electrónica", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1102843674, name:"Leydi Hernandez", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Quimica", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1038374645, name:"Paula Arias", administrator: true, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Quimica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1090000101, name:"Pedro Paramo", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1100908761, name:"Tom Sawyer", administrator: false, isStudent:true, owner:false, gender:'M',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")

Person.create(nident: 88082727, name:"Gonzalo Jimenez", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 71616161, name:"Leydi Cardozo", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Industrial", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 54333322, name:"Juanito Alimaña", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1010101010, name:"Pedro Navajas", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Mecánica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1111111111, name:"Hector Lavoe", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1222222222, name:"Celia Cruz", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Civil", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1333333333, name:"Miriam Urrego", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Sistemas", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1444444444, name:"María Peña", administrator: true, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Sistemas", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1555555555, name:"Nestor Nope", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1666666666, name:"Angie Beltran", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Agricola", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1777777777, name:"Pepito Perez", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Electrica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1888888888, name:"Magda Lourdes", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Electrica", city:"Manizales", aboutme:"No yet implements")
Person.create(nident: 1999999999, name:"Xavier Garden", administrator: false, isStudent:false, owner:false, gender:'M',  career:"Ingenieria Electrónica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1028846455, name:"Daniela Castillo", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Electrónica", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1098765432, name:"Ana Sanchez", administrator: false, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Quimica", city:"Medellín", aboutme:"No yet implements")
Person.create(nident: 1012345667, name:"Ana Mera", administrator: true, isStudent:false, owner:false, gender:'F',  career:"Ingenieria Quimica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1084367435, name:"Silvia Silva", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
Person.create(nident: 1109764322, name:"Sandra Castro", administrator: false, isStudent:true, owner:false, gender:'F',  career:"Ingenieria Mecatrónica", city:"Bogotá", aboutme:"No yet implements")
